### ISSUE TITLE
Custom Music Controls Not Coloured in ios 10 music app now playing view

### ISSUE THREAD

**Issue by maheshdj** [DavidGoldman/TweakAPIs#1]
I made a theme which replace Music Controls but Colorflow 3 not change colour of music controls in now playing views but colour is changing on Lockscreen view

**Comment by DavidGoldman** [comment]
Hey,

You should email me through Cydia (see: ColorFlow 3) for this and include more details about how the theme works.

Thanks

**Comment by maheshdj** [comment]
Ok thanks for responding

**Comment by maheshdj** [comment]
I mail you from cydia plz ASAP look into it
Thanks.
